import React from 'react';
import {useDoc} from '@docusaurus/plugin-content-docs/client';
import useBaseUrl from '@docusaurus/useBaseUrl';
import styles from './styles.module.css';

// Per-page "copy as Markdown" affordance (t08): fetches the raw Markdown
// twin of the current doc (generated by plugins/llms into /md/) into the
// clipboard, so a reader can paste the page straight into an agent prompt.
export default function CopyMarkdown(): React.ReactNode {
  const {metadata} = useDoc();
  const rawUrl = useBaseUrl(`md/${metadata.id}.md`);
  const [state, setState] = React.useState<'idle' | 'copied' | 'error'>('idle');

  const copy = async () => {
    try {
      const res = await fetch(rawUrl);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      await navigator.clipboard.writeText(await res.text());
      setState('copied');
    } catch {
      setState('error');
    }
    setTimeout(() => setState('idle'), 1600);
  };

  return (
    <div className={styles.row}>
      <span className={styles.tag}>MD</span>
      <button type="button" className={styles.btn} onClick={copy} aria-live="polite">
        {state === 'copied' ? 'copied ✓' : state === 'error' ? 'copy failed — retry' : 'copy as markdown'}
      </button>
      <a className={styles.link} href={rawUrl} target="_blank" rel="noopener noreferrer">
        view .md
      </a>
    </div>
  );
}
